spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: d400665f-0274-46fe-899b-38ed0885144a
        credential:
          client-id: dc8f3d14-355c-4223-80cb-23e938c26027
          client-secret: r1~8Q~337Lpk.Zl5HyebzmTTYIgU1Mja18XOUdcu
        app-id-uri: <Web-API-C-app-id-url>
        application-type: web_application_and_resource_server  # This is required.
        authorization-clients:
          graph:
            authorizationGrantType: authorization_code  # This is required.
            scopes:
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Directory.Read.All